"""store the full name of the user not seperate

Revision ID: 5721134d26dd
Revises: 3d3db3f3ad82
Create Date: 2022-12-22 17:58:59.981588

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5721134d26dd'
down_revision = '3d3db3f3ad82'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=128), nullable=True))
        batch_op.alter_column('phn',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
        batch_op.drop_column('lname')
        batch_op.drop_column('fname')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fname', sa.VARCHAR(length=128), nullable=True))
        batch_op.add_column(sa.Column('lname', sa.VARCHAR(length=128), nullable=True))
        batch_op.alter_column('phn',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
        batch_op.drop_column('name')

    # ### end Alembic commands ###
