"""changed name of person to user table

Revision ID: 79a61320a7b3
Revises: 85e0393d6e22
Create Date: 2022-12-18 14:26:47.052357

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79a61320a7b3'
down_revision = '85e0393d6e22'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=128), nullable=False),
    sa.Column('fname', sa.String(length=128), nullable=True),
    sa.Column('lname', sa.String(length=128), nullable=True),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('phn', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('username'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phn')
    )
    op.drop_table('person')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('person',
    sa.Column('username', sa.VARCHAR(length=50), nullable=False),
    sa.Column('password', sa.VARCHAR(length=128), nullable=False),
    sa.Column('fname', sa.VARCHAR(length=128), nullable=True),
    sa.Column('lname', sa.VARCHAR(length=128), nullable=True),
    sa.Column('email', sa.VARCHAR(), nullable=False),
    sa.Column('phn', sa.VARCHAR(length=10), nullable=False),
    sa.PrimaryKeyConstraint('username'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phn')
    )
    op.drop_table('user')
    # ### end Alembic commands ###
